### ISSUE TITLE
SudoSpawner & 'No JSON object could be decoded'

### ISSUE THREAD

**Issue by pierluigifailla** [jupyter/sudospawner#1]
Hi guys!
I try to use the SudoSpawner for JupyterHub. I followed these instructions: https://github.com/jupyter/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges all the tests was fine, but I've some weird error. 
I tried to run:
`sudo -u jhub_runner jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner --debug`
but when I try to login with my dedicated user I get:
`Unhandled error starting pierluigi_jupyter's server: No JSON object could be decoded`

I investigated a little in spawner.py and I figured out that error is at:
`return json.loads(data.decode('utf8'))`
and it is due to the fact that data is an empty string.

**cmd =** `['sudo', '-u', 'pierluigi_jupyter', '-nH', 'sudospawner']`
**kwargs =** `{'action': 'spawn', 'args': ['--user=pierluigi_jupyter', '--port=53251', '--cookie-name=jupyter-hub-token-pierluigi_jupyter', '--base-url=/user/pierluigi_jupyter', '--hub-prefix=/hub/', '--hub-api-url=http://localhost:8081/hub/api', '--ip=localhost'], 'env': {'USER': 'pierluigi_jupyter', 'HOME': '/home/pierluigi_jupyter', 'JPY_API_TOKEN': 'f32f975c2cf14bbe90362f9aa0f9f595', 'SHELL': '/bin/sh', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LANG': 'en_US.UTF-8'}}`
**json.dumps(kwargs).encode('utf8') =** `b'{"action": "spawn", "args": ["--user=pierluigi_jupyter", "--port=53251", "--cookie-name=jupyter-hub-token-pierluigi_jupyter", "--base-url=/user/pierluigi_jupyter", "--hub-prefix=/hub/", "--hub-api-url=http://localhost:8081/hub/api", "--ip=localhost"], "env": {"USER": "pierluigi_jupyter", "HOME": "/home/pierluigi_jupyter", "JPY_API_TOKEN": "f32f975c2cf14bbe90362f9aa0f9f595", "SHELL": "/bin/sh", "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "LANG": "en_US.UTF-8"}}'`
**data.decode('utf8') =** `''`

do you have any hint?

PS JupyterHub itself works fine without any issue.

**Comment by minrk** [comment]
Can you show a bit more of the log context?

**Comment by pierluigifailla** [comment]
Sure!

== LOG ==
$ sudo -u jhub_runner jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner --debug
[D 2015-05-29 17:03:28.331 JupyterHub application:242] Config changed:
[D 2015-05-29 17:03:28.331 JupyterHub application:243] {'JupyterHub': {'log_level': 10, 'spawner_class': 'sudospawner.SudoSpawner'}}
[I 2015-05-29 17:03:28.332 JupyterHub app:522] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[D 2015-05-29 17:03:28.332 JupyterHub app:549] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2015-05-29 17:03:28.372 JupyterHub app:260]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[I 2015-05-29 17:03:28.378 JupyterHub app:623] Not using whitelist. Any authenticated user will be allowed.
[D 2015-05-29 17:03:28.380 JupyterHub app:699] Loaded users:
    jhub_runner admin
    pierluigi_jupyter
[I 2015-05-29 17:03:28.387 JupyterHub app:1001] Hub API listening on http://localhost:8081/hub/
[I 2015-05-29 17:03:28.390 JupyterHub app:758] Starting proxy @ http://*:8000/
[D 2015-05-29 17:03:28.390 JupyterHub app:759] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', 'localhost', '--api-port', '8001', '--default-target', 'http://localhost:8081']
17:03:28.487 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
17:03:28.489 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[D 2015-05-29 17:03:28.494 JupyterHub app:787] Proxy started and appears to be up
[I 2015-05-29 17:03:28.495 JupyterHub app:1024] JupyterHub is now running at http://localhost:8000/
[I 2015-05-29 17:04:16.861 JupyterHub log:100] 200 GET /hub/ (@127.0.0.1) 28.73ms

=== cmd: ['sudo', '-u', 'pierluigi_jupyter', '-nH', 'sudospawner']


=== kwargs: {'action': 'spawn', 'args': ['--user=pierluigi_jupyter', '--port=53251', '--cookie-name=jupyter-hub-token-pierluigi_jupyter', '--base-url=/user/pierluigi_jupyter', '--hub-prefix=/hub/', '--hub-api-url=http://localhost:8081/hub/api', '--ip=localhost'], 'env': {'USER': 'pierluigi_jupyter', 'HOME': '/home/pierluigi_jupyter', 'JPY_API_TOKEN': 'f32f975c2cf14bbe90362f9aa0f9f595', 'SHELL': '/bin/sh', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LANG': 'en_US.UTF-8'}}


=== json.dumps: b'{"action": "spawn", "args": ["--user=pierluigi_jupyter", "--port=53251", "--cookie-name=jupyter-hub-token-pierluigi_jupyter", "--base-url=/user/pierluigi_jupyter", "--hub-prefix=/hub/", "--hub-api-url=http://localhost:8081/hub/api", "--ip=localhost"], "env": {"USER": "pierluigi_jupyter", "HOME": "/home/pierluigi_jupyter", "JPY_API_TOKEN": "f32f975c2cf14bbe90362f9aa0f9f595", "SHELL": "/bin/sh", "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "LANG": "en_US.UTF-8"}}'

[I 150529 17:04:23 mediator:62] Spawning /usr/bin/python3.3 -m jupyterhub.singleuser --user=pierluigi_jupyter --port=53251 --cookie-name=jupyter-hub-token-pierluigi_jupyter --base-url=/user/pierluigi_jupyter --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost

=== data: ''

[E 2015-05-29 17:04:23.955 JupyterHub orm:376] Unhandled error starting pierluigi_jupyter's server: No JSON object could be decoded
[E 2015-05-29 17:04:23.964 JupyterHub web:1496] Uncaught exception POST /hub/login?next= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'X-Forwarded-For': '127.0.0.1', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Cookie': '_ga=GA1.1.783766431.1415828907; __insp_slim=1415828906895; __insp_nv=true; __insp_ref=aHR0cDovL2xvY2FsaG9zdDo1MDAwL2ludGVybmFsL2RhdGFfZXhwbG9yYXRpb25fYW5ndWxhci8%3D; __insp_norec_sess=true; ucPref=%7B%22FIRST_VISIT%22%3Afalse%2C%22SELECTED_GEOGRAPHY%22%3A%22nyc%22%2C%22anonymous_user_id%22%3A%22542d8d1b421aa9043f056a5f%22%7D; lastVisited=%2Fresearch%2F; session="yEUXIJ83XUMcAAro9QuK3jYg9os=?_fresh=STAwCi4=&_id=UydlOTZiZmU3MzUyYWE5OWYwODdkZWRmYWU0OGY1Njk4NycKcDEKLg==&user_id=VjU0MmMzZGQ1ODU2OTkzMzQwNDcyMDQ3MApwMQou"', 'Content-Length': '45', 'X-Forwarded-Port': '8000', 'Referer': 'http://localhost:8000/hub/', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-Proto': 'http', 'Origin': 'http://localhost:8000', 'Host': 'localhost:8000', 'Accept-Language': 'en-US,en;q=0.8,it;q=0.6', 'Cache-Control': 'max-age=0', 'Connection': 'close', 'Content-Type': 'application/x-www-form-urlencoded'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.3/dist-packages/tornado/web.py", line 1415, in _execute
        result = yield result
      File "/usr/local/lib/python3.3/dist-packages/jupyterhub/handlers/login.py", line 66, in post
        yield self.spawn_single_user(user)
      File "/usr/local/lib/python3.3/dist-packages/jupyterhub/handlers/base.py", line 260, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/local/lib/python3.3/dist-packages/jupyterhub/orm.py", line 386, in spawn
        raise e
      File "/usr/local/lib/python3.3/dist-packages/jupyterhub/orm.py", line 367, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/pierluigi/development/sudospawner/sudospawner/spawner.py", line 65, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.env)
      File "/home/pierluigi/development/sudospawner/sudospawner/spawner.py", line 57, in do
        return json.loads(data.decode('utf8'))
      File "/usr/lib/python3.3/json/__init__.py", line 316, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.3/json/decoder.py", line 351, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.3/json/decoder.py", line 369, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

[D 2015-05-29 17:04:23.969 JupyterHub base:375] No template for 500
[E 2015-05-29 17:04:23.976 JupyterHub log:99] {
      "X-Forwarded-For": "127.0.0.1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Cookie": "_ga=GA1.1.783766431.1415828907; __insp_slim=1415828906895; __insp_nv=true; __insp_ref=aHR0cDovL2xvY2FsaG9zdDo1MDAwL2ludGVybmFsL2RhdGFfZXhwbG9yYXRpb25fYW5ndWxhci8%3D; __insp_norec_sess=true; ucPref=%7B%22FIRST_VISIT%22%3Afalse%2C%22SELECTED_GEOGRAPHY%22%3A%22nyc%22%2C%22anonymous_user_id%22%3A%22542d8d1b421aa9043f056a5f%22%7D; lastVisited=%2Fresearch%2F; session=\"yEUXIJ83XUMcAAro9QuK3jYg9os=?_fresh=STAwCi4=&_id=UydlOTZiZmU3MzUyYWE5OWYwODdkZWRmYWU0OGY1Njk4NycKcDEKLg==&user_id=VjU0MmMzZGQ1ODU2OTkzMzQwNDcyMDQ3MApwMQou\"",
      "Content-Length": "45",
      "X-Forwarded-Port": "8000",
      "Referer": "http://localhost:8000/hub/",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36",
      "Accept-Encoding": "gzip, deflate",
      "X-Forwarded-Proto": "http",
      "Origin": "http://localhost:8000",
      "Host": "localhost:8000",
      "Accept-Language": "en-US,en;q=0.8,it;q=0.6",
      "Cache-Control": "max-age=0",
      "Connection": "close",
      "Content-Type": "application/x-www-form-urlencoded"
    }
[E 2015-05-29 17:04:23.977 JupyterHub log:100] 500 POST /hub/login?next= (@127.0.0.1) 425.72ms

**Comment by pierluigifailla** [comment]
I figured out the error: my user does not have an home folder.
