### ISSUE TITLE
jupyterhub-singleuser used in mediator not configurable

### ISSUE THREAD

**Issue by mariusvniekerk** [jupyter/sudospawner#15]
In 

https://github.com/jupyter/sudospawner/blob/b66b7625d66a0fcd2d92f6b45bcb6f2cb29847df/sudospawner/mediator.py#L60

The `jupyterhub-singleuser` command is explicity used there.  Is there a way to configure it so that an absolute path to this can be provided.

I don't see an obvious place to change in order to make this configurable

**Comment by minrk** [comment]
It shouldn't be configurable. Actually, it shouldn't even be sensitive to PATH (this is a recently introduced bug, from when `python -m jupyterhub.singleuser` was removed).

#16 requires jupyterhub-singleuser to be the executable in the same directory as `sudospawner`.

**Comment by parente** [comment]
@minrk In the case where I want to keep my notebook server environment separate from my jupyterhub environment, it would be helpful to point to a script that activates the desired environment and then delegates the command line params to jupyterhub-singleuser. As it stands, I have to generate a script with that name, rename the actual juputerhub-singleuser script to something else, and then delegate to it.

Is there another way to accomplish conda / virtualenv activation before running jupyterhub-singleuser?
