### ISSUE TITLE
logs from spawned processes dropped

### ISSUE THREAD

**Issue by ndimiduk** [jupyter/sudospawner#9]
I'm using the sudospawner with great effect! One issue I'm having is that logs from the spawned processes are not making it back to the jupyterhub process. I tried [piping stderr](https://github.com/ndimiduk/sudospawner/commit/082f753a0bc161b4eeb36a185ee8e4fe1ea3a03b) back to the parent process, but that doesn't appear to help.

**Comment by minrk** [comment]
Yes, there was a problem where leaving stderr open prevented the mediator from exiting properly, so it's closed. This is the main source of debugging sudospawning being a nightmare. If there's a way to leave stderr open without reintroducing the problem, that would solve a lot of problems.

**Comment by ndimiduk** [comment]
Here's a [hack](https://github.com/ndimiduk/sudospawner/commit/4391f6e75d0a77c9c19aa7bc5a3ed81162a7b353) that collects process output *somewhere*.
